services:
  library-service:
    build:
      context: ../
      dockerfile: ./src/library.Dockerfile
    restart: always
    ports:
      - "8085:8085"
    env_file:
      - ../.env

  postgres:
    image: 'postgres:17'
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
      - ../migrations/migrations.sql:/docker-entrypoint-initdb.d/migrations.sql